import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:untitled/core/app_theme/app_colors/appcolors.dart';

class AppTheme {
  static List<ThemeData> themes = [lightTheme, darkTheme];

  static ThemeData lightTheme = ThemeData(
    brightness: Brightness.light,
    scaffoldBackgroundColor: LightColors.backgroundColor,
    primaryColor: LightColors.appPrimary,
    colorScheme: ColorScheme.light(
      primary: LightColors.appPrimary,
      secondary: LightColors.appSecondary,
      surface: LightColors.backgroundColor,
    ),
    textTheme: GoogleFonts.montserratTextTheme(ThemeData.light().textTheme),
    extensions: <ThemeExtension<AppColors>>[
      AppColors(
        lightPrimaryBase: LightColors.lightPrimaryBase,
        textPrimary: LightColors.textPrimary,
        isDarkMode: LightColors.isDarkMode,
        textBlack: LightColors.textBlack,
        subTextBlack: LightColors.subTextBlack,
        blackRed: LightColors.blackRed,
        dimBlack: LightColors.dimBlack,
        labelGray: LightColors.labelGray,
        textGray: LightColors.textGray,
        whiteBlue: LightColors.whiteBlue,
        lineGray: LightColors.lineGray,
        bgGray: LightColors.bgGray,
        cardBg: LightColors.cardBg,
        backgroundColorBlack: LightColors.backgroundColorBlack,
        backgroundColor: LightColors.backgroundColor,
        gradientBg: LightColors.gradientBg,
        appPrimary: LightColors.appPrimary,
        appPrimaryLight: LightColors.appPrimaryLight,
        appPrimaryDark: LightColors.appPrimaryDark,
        appPrimaryDarker: LightColors.appPrimaryDarker,
        appSecondary: LightColors.appSecondary,
        lightRed: LightColors.lightRed,
        lightPink: LightColors.lightPink,
        yellow: LightColors.yellow,
        lightGrayPink: LightColors.lightGrayPink,
        lightGreen: LightColors.lightGreen,
        darkerPrimary: LightColors.darkerPrimary,
        appPrimarySecondary: LightColors.appPrimarySecondary,
        darkestPrimary: LightColors.darkestPrimary,
        lightBlue: LightColors.lightBlue,
        errorRed: LightColors.errorRed,
        textSecondary: LightColors.textSecondary,
        appPrimary20: LightColors.appPrimary20,
        sheetBgPrimary: LightColors.sheetBgPrimary,
        lightPrimary: LightColors.lightPrimary,
        bgPrimary: LightColors.bgPrimary,
        white: LightColors.white,
      ),
    ],
  );

  static ThemeData darkTheme = ThemeData(
    brightness: Brightness.dark,
    scaffoldBackgroundColor: DarkColors.backgroundColor,
    primaryColor: DarkColors.appPrimary,
    colorScheme: ColorScheme.dark(
      primary: DarkColors.appPrimary,
      secondary: DarkColors.appSecondary,
      surface: DarkColors.backgroundColor,
    ),
    textTheme: GoogleFonts.montserratTextTheme(ThemeData.dark().textTheme),
    extensions: <ThemeExtension<AppColors>>[
      AppColors(
        isDarkMode: DarkColors.isDarkMode,
        textBlack: DarkColors.textBlack,
        subTextBlack: DarkColors.subTextBlack,
        blackRed: DarkColors.blackRed,
        backgroundColorBlack: DarkColors.backgroundColorBlack,
        dimBlack: DarkColors.dimBlack,
        labelGray: DarkColors.labelGray,
        textGray: DarkColors.textGray,
        whiteBlue: DarkColors.whiteBlue,
        lineGray: DarkColors.lineGray,
        bgGray: DarkColors.bgGray,
        cardBg: DarkColors.cardBg,
        backgroundColor: DarkColors.backgroundColor,
        gradientBg: DarkColors.gradientBg,
        textPrimary: DarkColors.textPrimary,
        lightPrimaryBase: DarkColors.lightPrimaryBase,
        appPrimary: DarkColors.appPrimary,
        appPrimaryLight: DarkColors.appPrimaryLight,
        appPrimaryDark: DarkColors.appPrimaryDark,
        appPrimaryDarker: DarkColors.appPrimaryDarker,
        appSecondary: DarkColors.appSecondary,
        lightRed: DarkColors.lightRed,
        lightPink: DarkColors.lightPink,
        yellow: DarkColors.yellow,
        lightGrayPink: DarkColors.lightGrayPink,
        lightGreen: DarkColors.lightGreen,
        darkerPrimary: DarkColors.darkerPrimary,
        appPrimarySecondary: DarkColors.appPrimarySecondary,
        darkestPrimary: DarkColors.darkestPrimary,
        lightBlue: DarkColors.lightBlue,
        errorRed: DarkColors.errorRed,
        textSecondary: DarkColors.textSecondary,
        appPrimary20: DarkColors.appPrimary20,
        sheetBgPrimary: DarkColors.sheetBgPrimary,
        lightPrimary: DarkColors.lightPrimary,
        bgPrimary: DarkColors.bgPrimary,
        white: DarkColors.white,
      ),
    ],
  );
}
